-- ============================================================
-- Hospital Management System - Database Schema
-- Engine: MySQL / MariaDB
-- Concept: One Patient -> Multiple Visits -> Treatments & Bills
-- ============================================================

CREATE DATABASE IF NOT EXISTS hospital_management
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE hospital_management;

-- ------------------------------------------------------------
-- 1. PATIENTS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patients (
    patient_id      INT AUTO_INCREMENT PRIMARY KEY,
    full_name       VARCHAR(100) NOT NULL,
    gender          ENUM('Male', 'Female', 'Other') NOT NULL,
    dob             DATE NOT NULL,
    phone           VARCHAR(15) NOT NULL,
    address         VARCHAR(255),
    blood_group     VARCHAR(5),
    registered_on   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_patient_phone CHECK (CHAR_LENGTH(phone) >= 7)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 2. DOCTORS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS doctors (
    doctor_id           INT AUTO_INCREMENT PRIMARY KEY,
    full_name           VARCHAR(100) NOT NULL,
    specialization       VARCHAR(100) NOT NULL,
    phone                VARCHAR(15) NOT NULL,
    consultation_fee    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    is_available         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_doctor_fee CHECK (consultation_fee >= 0)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 3. VISITS  (OPD / token queue, one row per patient visit)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS visits (
    visit_id        INT AUTO_INCREMENT PRIMARY KEY,
    patient_id      INT NOT NULL,
    doctor_id       INT NOT NULL,
    token_number    INT NOT NULL,
    visit_date      DATE NOT NULL,
    visit_time      TIME NOT NULL DEFAULT (CURRENT_TIME),
    status          ENUM('Waiting', 'In Consultation', 'Completed', 'Cancelled')
                        NOT NULL DEFAULT 'Waiting',
    diagnosis       TEXT,
    notes           TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE KEY uq_doctor_date_token (doctor_id, visit_date, token_number)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 3b. TOKEN COUNTERS
-- One row per (doctor, day). Tokens are generated by atomically
-- incrementing this single-row counter (INSERT ... ON DUPLICATE KEY
-- UPDATE) instead of scanning/locking the visits table with
-- SELECT MAX() ... FOR UPDATE, which deadlocks under concurrent
-- receptionist requests (see defect log in docs/DEFECTS.md).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS token_counters (
    doctor_id   INT NOT NULL,
    visit_date  DATE NOT NULL,
    last_token  INT NOT NULL DEFAULT 0,
    PRIMARY KEY (doctor_id, visit_date),
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 4. MEDICINES (pharmacy master / inventory)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS medicines (
    medicine_id     INT AUTO_INCREMENT PRIMARY KEY,
    medicine_name   VARCHAR(100) NOT NULL UNIQUE,
    unit_price      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    stock_quantity  INT NOT NULL DEFAULT 0,
    CONSTRAINT chk_medicine_price CHECK (unit_price >= 0),
    CONSTRAINT chk_medicine_stock CHECK (stock_quantity >= 0)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 5. PRESCRIPTIONS (medicines prescribed during a visit)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS prescriptions (
    prescription_id INT AUTO_INCREMENT PRIMARY KEY,
    visit_id        INT NOT NULL,
    medicine_id     INT NOT NULL,
    dosage          VARCHAR(50),
    duration_days   INT NOT NULL DEFAULT 1,
    quantity        INT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (visit_id) REFERENCES visits(visit_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (medicine_id) REFERENCES medicines(medicine_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_prescription_qty CHECK (quantity > 0)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- 6. BILLING (one bill per visit)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS billing (
    bill_id             INT AUTO_INCREMENT PRIMARY KEY,
    visit_id            INT NOT NULL UNIQUE,
    consultation_fee    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    medicine_charges    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_amount        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    payment_status       ENUM('Pending', 'Paid') NOT NULL DEFAULT 'Pending',
    bill_date            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (visit_id) REFERENCES visits(visit_id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Helpful indexes for common lookups
-- ------------------------------------------------------------
CREATE INDEX idx_visits_patient ON visits(patient_id);
CREATE INDEX idx_visits_doctor_date ON visits(doctor_id, visit_date);
CREATE INDEX idx_prescriptions_visit ON prescriptions(visit_id);
CREATE INDEX idx_patients_phone ON patients(phone);
